Block.defineBlock(16,"铜矿石","铜矿石",64,true,0);
Player.addItemCreativeInv(200,1,0);
Block.setDestroyTime(200,1);
Block.defineBlock(15,"铁矿石","铁矿石",64,true,0);
Player.addItemCreativeInv(15,1,0);
Block.setDestroyTime(15,1);
Block.defineBlock(73,"银矿石","银矿石",64,true,0);
Player.addItemCreativeInv(73,1,0);
Block.setDestroyTime(73,1);
Block.defineBlock(14,"金矿石","金矿石",64,true,0);
Player.addItemCreativeInv(14,1,0);
Block.setDestroyTime(14,1);
Block.defineBlock(200,"陨铁矿石","陨铁矿石",64,true,0);
Player.addItemCreativeInv(56,1,0);
Block.setDestroyTime(56,1);
Block.defineBlock(1,"石块","岩石块",64,true,0);
Player.addItemCreativeInv(1,1,0);
Block.setDestroyTime(1,1);
Block.defineBlock(4,"岩石块","岩石块",64,true,0);
Player.addItemCreativeInv(4,1,0);
Block.setDestroyTime(4,1);
Block.defineBlock(21,"黑球","黑球",64,true,0);
Player.addItemCreativeInv(21,1,0);
Block.setDestroyTime(21,1);
Block.defineBlock(201,"锡矿石","锡矿石",64,true,0);
Player.addItemCreativeInv(201,1,0);
Block.setDestroyTime(201,1);
Block.defineBlock(202,"铅矿石","铅矿石",64,true,0);
Player.addItemCreativeInv(202,1,0);
Block.setDestroyTime(202,1);
Block.defineBlock(203,"铂金矿石","铂金矿石",64,true,0);
Player.addItemCreativeInv(203,1,0);
Block.setDestroyTime(203,1);
Block.defineBlock(204,"钨金矿石","钨金矿石",64,true,0);
Player.addItemCreativeInv(204,1,0);
Block.setDestroyTime(204,1);
Block.defineBlock(159,"血腥石块","血腥石块",64,true,0);
Player.addItemCreativeInv(159,1,0);
Block.setDestroyTime(159,1);
Block.defineBlock(172,"血石块","血腥石块",64,true,0);
Player.addItemCreativeInv(172,1,0);
Block.setDestroyTime(172,1);
function modTick(){
if(Player.getCarriedItem()!=270){
Block.setDestroyTime(16,-1);
Block.setDestroyTime(1,-1);
Block.setDestroyTime(4,1);
}
if(Player.getCarriedItem()==270){
Block.setDestroyTime(16,1);
Block.setDestroyTime(1,1);
Block.setDestroyTime(4,1);
}
if(Player.getCarriedItem()!=911){
Block.setDestroyTime(15,-1);
Block.setDestroyTime(73,-1);
Block.setDestroyTime(14,-1);
Block.setDestroyTime(201,-1);
Block.setDestroyTime(202,-1);
}
if(Player.getCarriedItem()==911){
Block.setDestroyTime(15,1);
Block.setDestroyTime(73,1);
Block.setDestroyTime(14,1);
Block.setDestroyTime(201,1);
Block.setDestroyTime(202,1);
}
if(Player.getCarriedItem()!=916){
Block.setDestroyTime(21,-1);
}
if(Player.getCarriedItem()==916){
Block.setDestroyTime(21,1);
}
if(Player.getCarriedItem()!=285){
Block.setDestroyTime(200,-1);
}
if(Player.getCarriedItem()==285){
Block.setDestroyTime(200,1);
}
}
function destroyBlock(x,y,z,side/*破坏面*/) {
if(Player.getCarriedItem()==916&&Player.getPointedBlockId()==21){
clientMessage("陨铁矿石已落地");
setTile(Player.getPointedBlockX(),Player.getPointedBlockY(),Player.getPointedBlockZ(),200,0);
setTile(Player.getPointedBlockX()+1,Player.getPointedBlockY(),Player.getPointedBlockZ(),200,0);
setTile(Player.getPointedBlockX()-1,Player.getPointedBlockY(),Player.getPointedBlockZ(),200,0);
setTile(Player.getPointedBlockX(),Player.getPointedBlockY(),Player.getPointedBlockZ()+1,200,0);
setTile(Player.getPointedBlockX(),Player.getPointedBlockY(),Player.getPointedBlockZ()-1,200,0);
setTile(Player.getPointedBlockX(),Player.getPointedBlockY()+1,Player.getPointedBlockZ(),200,0);
setTile(Player.getPointedBlockX(),Player.getPointedBlockY()-1,Player.getPointedBlockZ(),200,0);
}
}
function startDestroyBlock(x,y,z,side/*破坏面*/) {
if(Player.getPointedBlockId()==200){
setTile(Player.getPointedBlockX(),Player.getPointedBlockId(),Player.getPointedBlockZ(),51,0);
}
}