矿物生成1 = function(ID,特殊值,数量,高度,替换方块){
 生成=0;生成++;
 几率=Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random());
 x=getPlayerX()+Math.random()*256
 y=Math.random()*高度
 z=getPlayerZ()+Math.random()*256
 if(getTile(x,y,z)==替换方块){
  if(生成<=数量){
   setTile(x,y,z,ID,特殊值);
   if(几率==0){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y,z+1,ID,特殊值);
    setTile(x+1,y,z+1,ID,特殊值);
    setTile(x,y+1,z,ID,特殊值);
    setTile(x+1,y-1,z+1,ID,特殊值);
   }
   if(几率==1){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==2){
    setTile(x,y-1,z,ID,特殊值);
    setTile(x+1,y-1,z,ID,特殊值);
    setTile(x,y-1,z+1,ID,特殊值);
   }
   if(几率==3){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
   }
   if(几率==4){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==5){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==6){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==7){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==8){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==9){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==10){
     setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
  }
  else if(生成>数量){生成=0}
 }
}
矿物生成2 = function(ID,特殊值,数量,高度,替换方块){
 生成=0;生成++;
 几率=Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random());
 x=getPlayerX()+Math.random()*256
 y=Math.random()*高度
 z=getPlayerZ()-Math.random()*256
 if(getTile(x,y,z)==替换方块){
  if(生成<=数量){
   setTile(x,y,z,ID,特殊值);
   if(几率==0){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y,z+1,ID,特殊值);
    setTile(x+1,y,z+1,ID,特殊值);
    setTile(x,y+1,z,ID,特殊值);
    setTile(x+1,y-1,z+1,ID,特殊值);
   }
   if(几率==1){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==2){
    setTile(x,y-1,z,ID,特殊值);
    setTile(x+1,y-1,z,ID,特殊值);
    setTile(x,y-1,z+1,ID,特殊值);
   }
   if(几率==3){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
   }
   if(几率==4){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==5){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==6){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==7){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==8){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==9){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==10){
     setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
  }
  else if(生成>数量){生成=0}
 }
}
矿物生成3 = function(ID,特殊值,数量,高度,替换方块){
 生成=0;生成++;
 几率=Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random());
 x=getPlayerX()-Math.random()*256
 y=Math.random()*高度
 z=getPlayerZ()+Math.random()*256
 if(getTile(x,y,z)==替换方块){
  if(生成<=数量){
   setTile(x,y,z,ID,特殊值);
   if(几率==0){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y,z+1,ID,特殊值);
    setTile(x+1,y,z+1,ID,特殊值);
    setTile(x,y+1,z,ID,特殊值);
    setTile(x+1,y-1,z+1,ID,特殊值);
   }
   if(几率==1){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==2){
    setTile(x,y-1,z,ID,特殊值);
    setTile(x+1,y-1,z,ID,特殊值);
    setTile(x,y-1,z+1,ID,特殊值);
   }
   if(几率==3){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
   }
   if(几率==4){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==5){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==6){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==7){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==8){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==9){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==10){
     setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
  }
  else if(生成>数量){生成=0}
 }
}
矿物生成4 = function(ID,特殊值,数量,高度,替换方块){
 生成=0;生成++;
 几率=Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random())+Math.round(Math.random());
 x=getPlayerX()-Math.random()*256
 y=Math.random()*高度
 z=getPlayerZ()-Math.random()*256
 if(getTile(x,y,z)==替换方块){
  if(生成<=数量){
   setTile(x,y,z,ID,特殊值);
   if(几率==0){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y,z+1,ID,特殊值);
    setTile(x+1,y,z+1,ID,特殊值);
    setTile(x,y+1,z,ID,特殊值);
    setTile(x+1,y-1,z+1,ID,特殊值);
   }
   if(几率==1){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==2){
    setTile(x,y-1,z,ID,特殊值);
    setTile(x+1,y-1,z,ID,特殊值);
    setTile(x,y-1,z+1,ID,特殊值);
   }
   if(几率==3){
    setTile(x+1,y,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
   }
   if(几率==4){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==5){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
   if(几率==6){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==7){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
   }
   if(几率==8){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==9){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
   }
   if(几率==10){
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x-1,y-1,z,ID,特殊值);
    setTile(x,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z,ID,特殊值);
    setTile(x,y-2,z,ID,特殊值);
    setTile(x,y,z-2,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-1,y-2,z-1,ID,特殊值);
    setTile(x-2,y-1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-2,ID,特殊值);
    setTile(x-1,y-2,z-2,ID,特殊值);
    setTile(x-1,y+1,z,ID,特殊值);
    setTile(x,y+1,z-1,ID,特殊值);
    setTile(x,y,z,ID,特殊值);
    setTile(x-1,y,z,ID,特殊值);
    setTile(x,y,z-1,ID,特殊值);
    setTile(x-1,y,z-1,ID,特殊值);
    setTile(x-2,y+1,z,ID,特殊值);
    setTile(x,y-1,z,ID,特殊值);
    setTile(x,y+1,z-2,ID,特殊值);
    setTile(x-1,y+1,z-1,ID,特殊值);
    setTile(x-1,y-1,z-1,ID,特殊值);
    setTile(x-2,y,z-1,ID,特殊值);
    setTile(x-1,y,z-2,ID,特殊值);
    setTile(x-1,y-3,z-2,ID,特殊值);
   }
  }
  else if(生成>数量){生成=0}
 }
}

矿物生成 = function(ID,特殊值,数量,高度,替换方块){
 矿物生成1(ID,特殊值,数量,高度,替换方块);
 矿物生成2(ID,特殊值,数量,高度,替换方块);
 矿物生成3(ID,特殊值,数量,高度,替换方块);
 矿物生成4(ID,特殊值,数量,高度,替换方块);
}

function modTick(){
矿物生成(201,0,1500,128,1)
矿物生成(202,0,750,128,1)
矿物生成(203,0,700,80,1)
矿物生成(204,0,500,80,129)
矿物生成(1,0,1500,128,201)
矿物生成(1,0,1500,128,202)
矿物生成(1,0,1500,128,203)
矿物生成(1,0,1500,128,204)
}